"""Add sent_at and report_path to weekly_reports

Revision ID: 3a698ed3dfbe
Revises: 7e5d578572a8
Create Date: 2026-07-28 22:24:24.787697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a698ed3dfbe'
down_revision: Union[str, Sequence[str], None] = '7e5d578572a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_reports', sa.Column('report_path', sa.String(), nullable=True))
    op.add_column('weekly_reports', sa.Column('sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_reports', 'sent_at')
    op.drop_column('weekly_reports', 'report_path')
    # ### end Alembic commands ###
